/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

import javax.swing.JOptionPane;

/**
 *
 * @author tangRufus@gmail.com
 */
public class CalculatorGUI extends javax.swing.JFrame {
    
    private char state;
    private double operand1, operand2;
    private char operator;
    
    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
        
       /**
        * This constructor is already provided to you by NetBeans once you built your 
        * GUI. You just need revise it to initialize the extra instance variables state as 
        * ‘A’, operand1 and operand2 as 0.0, and operator as ‘=’.
        */ 
        
        state = 'A';
        operand1 = 0.0;
        operand2 = 0.0;
    }

    private void digitPressed(int d) {
        /**
         * This private method should be called by the event handling methods of the digit 
         * buttons. Parameter d is the digit on the button just pressed. You can assume that 
         * d is always 0 to 9 (inclusive). In this method, depending on the current state, you 
         * should update (a) the state if needed, (b) operands 1 or 2, and (c) the display text 
         * field of the calculator accordingly. See Table 1 and Figure 2 for example.
         */
        
        char oldState = state;
        //(a) the state if needed
        state = (state == 'A') ? 'B' : state;
        state = (state == 'C') ? 'D' : state;
        state = (state == 'E') ? 'B' : state;
         
        //(b) operands 1 or 2
        if (state == 'B') {
            operand1 = operand1*10 + d;
        } else if (state == 'D' && oldState == 'D') {
            operand2 = operand2*10 + d;
        } else if (state == 'D' && oldState != 'D') {
            operand2 = d;
        }
        
        //(c) the display text field of the calculator accordingly.
         if (state == 'B') {
             if ((operand1 == Math.floor(operand1)) && !Double.isInfinite(operand1)) {
                mainDisplay.setText(Integer.toString((int) Math.floor(operand1)));
             } else {
                mainDisplay.setText(String.format("%.1f", operand1));
             }
        } else if (state == 'D') {
              if ((operand2 == Math.floor(operand2)) && !Double.isInfinite(operand2)) {
                 mainDisplay.setText(Integer.toString((int) Math.floor(operand2)));
             } else {
                mainDisplay.setText(String.format("%.1f", operand2));
             }
        }
    }

    private void operatorPressed(char op) {
        //In case of invalid user input (such as pressing the + button in state C),
        //you should prompt a warning dialog using: 
        //JOptionPane.showMessageDialog(this, "Invalid input!");
        if ( state == 'A' || state == 'C') {
            JOptionPane.showMessageDialog(this, "Invalid input!");
            return;
        }
        
        if ( state != 'D' && op =='=') {
            JOptionPane.showMessageDialog(this, "Invalid input!");
            return;
        }
        
        //(b) operand 1
        if ( state == 'D') {
            switch(operator) {
                case '+':
                    operand1 += operand2;
                    break;
                case '-':
                    operand1 -= operand2;
                    break;
                case '*':
                    operand1 *= operand2;
                    break;
                case '/':
                    operand1 /= operand2;
                    break;
            }
        }
        
        //(a) the state if needed
        state = (state == 'B') ? 'C' : state;
        state = (state == 'D') ? 'C' : state;
        state = (state == 'E') ? 'C' : state;
        state = (op == '=') ? 'E' : state;
        
        //(c) the last pressed operator and its corresponding text field
        operator = op;
        opDisplay.setText(Character.toString(op));
        
        //(d) the display text field of the calculation (i.e. format to one 
        //decimal place only) accordingly. 
        mainDisplay.setText(String.format("%.1f", operand1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainDisplay = new javax.swing.JTextField();
        digiButton8 = new javax.swing.JButton();
        digiButton9 = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        times = new javax.swing.JButton();
        digiButton6 = new javax.swing.JButton();
        digiButtonv5 = new javax.swing.JButton();
        digiButton4 = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        digiButton3 = new javax.swing.JButton();
        digiButton2 = new javax.swing.JButton();
        digiButton1 = new javax.swing.JButton();
        opDisplay = new javax.swing.JTextField();
        digiButton0 = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        digiButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        mainDisplay.setEditable(false);
        mainDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mainDisplay.setText("0");

        digiButton8.setMnemonic('8');
        digiButton8.setLabel("8");
        digiButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                digiButton8OnClickHandler(evt);
            }
        });

        digiButton9.setMnemonic('9');
        digiButton9.setLabel("9");
        digiButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                digiButton9OnClickHandler(evt);
            }
        });

        divide.setText("/");
        divide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                operatorDivideButtonsOnClickHandler(evt);
            }
        });

        times.setText("*");
        times.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                operatorTimesButtonsOnClickHandler(evt);
            }
        });

        digiButton6.setMnemonic('6');
        digiButton6.setLabel("6");
        digiButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                digiButton6OnClickHandler(evt);
            }
        });

        digiButtonv5.setMnemonic('5');
        digiButtonv5.setLabel("5");
        digiButtonv5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                digiButton5OnClickHandler(evt);
            }
        });

        digiButton4.setMnemonic('4');
        digiButton4.setLabel("4");
        digiButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                digiButton4OnClickHandler(evt);
            }
        });

        minus.setText("-");
        minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                operatorMiniusButtonsOnClickHandler(evt);
            }
        });

        digiButton3.setMnemonic('3');
        digiButton3.setLabel("3");
        digiButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                digiButton3OnClickHandler(evt);
            }
        });

        digiButton2.setMnemonic('2');
        digiButton2.setLabel("2");
        digiButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                digiButton2OnClickHandler(evt);
            }
        });

        digiButton1.setMnemonic('1');
        digiButton1.setText("1");
        digiButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                digiButton1OnClickHandler(evt);
            }
        });

        opDisplay.setEditable(false);
        opDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        digiButton0.setMnemonic('0');
        digiButton0.setText("0");
        digiButton0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                digiButton0OnClickHandler(evt);
            }
        });

        equal.setText("=");
        equal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                operatorEqualButtonsOnClickHandler(evt);
            }
        });

        plus.setText("+");
        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                operatorPlusButtonsOnClickHandler(evt);
            }
        });

        digiButton7.setMnemonic('7');
        digiButton7.setText("7");
        digiButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                digiButton7OnClickHandler(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(digiButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(digiButtonv5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(digiButton6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(times, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(opDisplay)
                                    .add(digiButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(layout.createSequentialGroup()
                                        .add(digiButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(digiButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(minus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(layout.createSequentialGroup()
                                        .add(digiButton0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(equal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(plus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, mainDisplay)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(digiButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(12, 12, 12)
                                .add(digiButton8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(digiButton9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(divide, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(mainDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(digiButton8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(digiButton9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(divide, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(digiButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(digiButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(digiButtonv5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(digiButton6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(times, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(digiButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(digiButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(digiButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(minus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(opDisplay, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(digiButton0, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(equal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(plus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void digiButton8OnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digiButton8OnClickHandler
        // TODO add your handling code here:
         digitPressed(8); 
    }//GEN-LAST:event_digiButton8OnClickHandler

    private void digiButton9OnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digiButton9OnClickHandler
        // TODO add your handling code here:
         digitPressed(9);
    }//GEN-LAST:event_digiButton9OnClickHandler

    private void digiButton7OnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digiButton7OnClickHandler
        // TODO add your handling code here:
         digitPressed(7);
    }//GEN-LAST:event_digiButton7OnClickHandler

    private void digiButton6OnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digiButton6OnClickHandler
        // TODO add your handling code here:
         digitPressed(6);
    }//GEN-LAST:event_digiButton6OnClickHandler

    private void digiButton5OnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digiButton5OnClickHandler
        // TODO add your handling code here:
         digitPressed(5);
    }//GEN-LAST:event_digiButton5OnClickHandler

    private void digiButton4OnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digiButton4OnClickHandler
        // TODO add your handling code here:
         digitPressed(4);
    }//GEN-LAST:event_digiButton4OnClickHandler

    private void digiButton1OnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digiButton1OnClickHandler
        // TODO add your handling code here:
         digitPressed(1);
    }//GEN-LAST:event_digiButton1OnClickHandler

    private void digiButton2OnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digiButton2OnClickHandler
        // TODO add your handling code here:
         digitPressed(2);
    }//GEN-LAST:event_digiButton2OnClickHandler

    private void digiButton3OnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digiButton3OnClickHandler
        // TODO add your handling code here:
         digitPressed(3);
    }//GEN-LAST:event_digiButton3OnClickHandler

    private void digiButton0OnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_digiButton0OnClickHandler
        // TODO add your handling code here:
         digitPressed(0);
    }//GEN-LAST:event_digiButton0OnClickHandler

    private void operatorDivideButtonsOnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operatorDivideButtonsOnClickHandler
        // TODO add your handling code here:
        operatorPressed('/');
    }//GEN-LAST:event_operatorDivideButtonsOnClickHandler

    private void operatorTimesButtonsOnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operatorTimesButtonsOnClickHandler
        // TODO add your handling code here:
         operatorPressed('*');
    }//GEN-LAST:event_operatorTimesButtonsOnClickHandler

    private void operatorMiniusButtonsOnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operatorMiniusButtonsOnClickHandler
        // TODO add your handling code here:
         operatorPressed('-');
    }//GEN-LAST:event_operatorMiniusButtonsOnClickHandler

    private void operatorPlusButtonsOnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operatorPlusButtonsOnClickHandler
        // TODO add your handling code here:
         operatorPressed('+');
    }//GEN-LAST:event_operatorPlusButtonsOnClickHandler

    private void operatorEqualButtonsOnClickHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operatorEqualButtonsOnClickHandler
        // TODO add your handling code here:
         operatorPressed('=');
    }//GEN-LAST:event_operatorEqualButtonsOnClickHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton digiButton0;
    private javax.swing.JButton digiButton1;
    private javax.swing.JButton digiButton2;
    private javax.swing.JButton digiButton3;
    private javax.swing.JButton digiButton4;
    private javax.swing.JButton digiButton6;
    private javax.swing.JButton digiButton7;
    private javax.swing.JButton digiButton8;
    private javax.swing.JButton digiButton9;
    private javax.swing.JButton digiButtonv5;
    private javax.swing.JButton divide;
    private javax.swing.JButton equal;
    private javax.swing.JTextField mainDisplay;
    private javax.swing.JButton minus;
    private javax.swing.JTextField opDisplay;
    private javax.swing.JButton plus;
    private javax.swing.JButton times;
    // End of variables declaration//GEN-END:variables
}
